<?php

declare(strict_types=1);

namespace Shanginn\AbdulSalesman\Anthropic\Message;

use Crell\Serde\Attributes\Field;

/**
 * Represents a text content block in an API response.
 */
final class TextContent implements ResponseMessageContentInterface
{
    /**
     * @param string $type The type of content block, always "text" for this class.
     * @param string $text The text content generated by the model.
     */
    public function __construct(
        public string $text,
    ) {}
}